apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kopi
  labels:
    app: postgres
    app.kubernetes.io/part-of: kopi-tools
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
