apiVersion: v1
kind: Service
metadata:
  name: kopi-auth
  namespace: kopi
  labels:
    app: kopi-auth
    app.kubernetes.io/part-of: kopi-tools
spec:
  selector:
    app: kopi-auth
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
